### ISSUE TITLE
ACK is invalid! ACK=07; Excepted=AA Pi8 huawei gra l09 

### ISSUE THREAD

**Issue by kona7720** [mashed-potatoes/PotatoNV#110]
im trying to unlock my huawei p8 gra l09 (2015)
but keep getting this error everytime i try to unlock could anyone maybe help me?
![Knipsel](https://user-images.githubusercontent.com/65238359/146566520-3fe5097b-b971-40b9-8a89-e61904d624ea.PNG)

**Comment by mashed-potatoes** [comment]
@kona7720 use 65x (A)
