### ISSUE TITLE
Test for Nova 3i

### ISSUE THREAD

**Issue by SerjSX** [mashed-potatoes/PotatoNV#29]
Hello! Please test it for Nova 3i (not Nova 3e, they are different.) before I proceed the process. And hopefully the Linux version soon (ik someone else already said it)!

**Comment by iGOR121** [comment]
nova 3i is p20 lite..

**Comment by SerjSX** [comment]
@mashed-potatoes I just saw this https://github.com/mashed-potatoes/PotatoNV/issues/5#issuecomment-670304138 Nova 3i has 710 :( I hope you find a way like DC Unlocker has! Thanks for this project :).
