### ISSUE TITLE
Works on Honor 7 Lite (NEM model)

### ISSUE THREAD

**Issue by SerjSX** [mashed-potatoes/PotatoNV#30]
I'm a moderator on the XDA's Discord server and I announced this project there, so if the users test this tool and it works I will let you know in the Issues. For now one tested and Honor 7 Lite, the NEM model, works and bootloader is unlocked!

Thank you for this tool, XDA users with Huawei devices on the Discord server are very happy now hehe (no more paying for DC Unlocker!) :D.

**Comment by SerjSX** [comment]
Update on issue:
- Kirin 659A and B are confirmed to be working on the honor 7 lite.
- 960 writes an additional image, it doesn't work.

**Comment by mashed-potatoes** [comment]
Thank you!
