### ISSUE TITLE
Please add support for Honor 10 Kirin 970

### ISSUE THREAD

**Issue by radjm** [mashed-potatoes/PotatoNV#34]
Thank you for efforts!
I have tried available bootloaders to unlock Honor 10 Kirin 970, but the error log show that it is not compatible with Kirin 970.
I would be grateful if you can add this support.
By the way I have assumptions how to scale the usage of your product.

**Comment by mashed-potatoes** [comment]
Try DC-Phoenix & HCU w/ software testpoint.
https://github.com/mashed-potatoes/PotatoNV/issues/5#issuecomment-670304138
