### ISSUE TITLE
P9 Lite

### ISSUE THREAD

**Issue by uvzen** [mashed-potatoes/PotatoNV#40]
Hi, thanks for creating something so great. I have unlocked my Huawei P10 device, but I have a question about Huawei P9 Lite devices. On the specs page, this device has a Kirin 650 processor
Link: https://www.gsmarena.com/huawei_p9_lite-7983.php

Will I unlock this device by selecting Kirin 659 A or B?

**Comment by BurnyLlama** [comment]
I think I used A.
