### ISSUE TITLE
Uploading bootloader times out

### ISSUE THREAD

**Issue by 2BDia** [mashed-potatoes/PotatoNV#43]
Hi,

I'm trying to unlock my Huawei P8 lite (ALE-L21) but I can't get past the "Uploading hisi659a bootloader" step (see screen)
![image](https://user-images.githubusercontent.com/78406811/111411679-4647c300-86db-11eb-8813-aa1efb09c3b3.png)
For info "Délai d'attente de l'écriture dépassé" basically means "Time out"
It's probably due to ADB but I have no idea how to use it and install it, if someone would be willing to help. Ports are showing up with COM so it should be ok (?)
![image](https://user-images.githubusercontent.com/78406811/111411712-565fa280-86db-11eb-8d99-9e22e5cafd9c.png)

Little update : when the phone is on like usual, the device shows up in the list of connected adb devices, however I don't get anything when booting the phone with the testing point method (probably the issue?)
![image](https://user-images.githubusercontent.com/78406811/111415063-78f4ba00-86e1-11eb-8f87-573172163119.png)

Thanks a lot in advance.

**Comment by 2BDia** [comment]
Little update : when the phone is on like usual, the device shows up in the list of connected adb devices, however I don't get anything when booting the phone with the testing point method
![image](https://user-images.githubusercontent.com/78406811/111414915-261b0280-86e1-11eb-94e7-a294b2343c7f.png)

Again, thanks in advance :)

**Comment by mashed-potatoes** [comment]
https://github.com/mashed-potatoes/PotatoNV/issues/39#issuecomment-803104732

**Comment by BudDeuce** [comment]
Use a newer version of PotatoNV.

**Comment by BudDeuce** [comment]
@2BDia Use a newer version of PotatoNV.
