### ISSUE TITLE
Kirin 955

### ISSUE THREAD

**Issue by Picoseconds** [mashed-potatoes/PotatoNV#45]
kirin 955, use potatonv?

**Comment by mashed-potatoes** [comment]
Just try different bootloaders

**Comment by Picoseconds** [comment]
So possible?

**Comment by mashed-potatoes** [comment]
Maybe

**Comment by NetviperZ** [comment]
any update with this kirin 955 ?

**Comment by mohahack** [comment]
I used a kirin950 bootloader on Huawei P9 (Kirin955) and it works fine

**Comment by Picoseconds** [comment]
Really? Great!

**Comment by Picoseconds** [comment]
If that's true, I will close this issue

**Comment by Picoseconds** [comment]
@mohahack Where is the testpoint

**Comment by NetviperZ** [comment]
I just unlocked my P9 a week ago and i can confirm that kirin950 bootloader working fine with my Huawei P9 (EVA-L19)


![P9 testpoint:](https://user-images.githubusercontent.com/11739817/113895121-90930000-97c0-11eb-9105-6692ed15c59f.jpg)

![P9 Unlock](https://user-images.githubusercontent.com/11739817/113895312-c2a46200-97c0-11eb-84d7-cf370f98fc63.PNG)

**Comment by mashed-potatoes** [comment]
@NetviperZ, thank you!
