### ISSUE TITLE
Can you add the P30 Pro (VOG-L29 / Kirin 980) ?

### ISSUE THREAD

**Issue by galaxyrun** [mashed-potatoes/PotatoNV#48]
Can you please add the P30 Pro, as there is no available method to unlock the bootloader at the moment?

**Comment by mashed-potatoes** [comment]
See #5

**Comment by mashed-potatoes** [comment]
> as there is no available method to unlock the bootloader at the moment

https://hcu-client.com/hcu-features-by-tp-xloader/
