### ISSUE TITLE
Can you please tell , how to use this files , much thanks in advance :)

### ISSUE THREAD

**Issue by titanx980ti** [mashed-potatoes/PotatoNV#6]
it would be better , if it has a detailed instructions on how to open this file

**Comment by micbanand** [comment]
https://github.com/mashed-potatoes/PotatoNV/releases
there are 2 links in xda thread. Think you miss the one I linked here

**Comment by micbanand** [comment]
> it would be better , if it has a detailed instructions on how to open this file

https://github.com/mashed-potatoes/PotatoNV/releases
there are 2 links in xda thread. Think you miss the one I linked here

**Comment by titanx980ti** [comment]
i saw that , for some reason my phone is detected only in fastboot , later gives a output saying , FP locked !, will this help in getting the boot loader code ?

**Comment by micbanand** [comment]
read up on oem lock. (is in dev options) and basic adb. and I will recommend not logged in to google account and no use of code. 
Out

**Comment by mashed-potatoes** [comment]
Please follow the guide: https://github.com/mashed-potatoes/PotatoNV/wiki/How-to-use-PotatoNV

**Comment by titanx980ti** [comment]
> 
> 
> read up on oem lock. (is in dev options) and basic adb. and I will recommend not logged in to google account and no use of code.
> Out

nope , i have not logged in with my google account , My FRP is unlocked , But my phone is locked ! , that is boot loader ,where i need oem unlock code to unlock it.

**Comment by mashed-potatoes** [comment]
Since I have not heard back from you, I'm closing this issue.
