### ISSUE TITLE
Auto Re-Locked

### ISSUE THREAD

**Issue by AhsanBulbul00** [mashed-potatoes/PotatoNV#60]
Device: Huawei GR 5 2017 (BLL-L22) [ Kirin65(A) ; EMUI: 05 ]

When went for flashing twrp after successful unlocking,
`fastboot: FAILED (remote: image verification error) `
```
fastboot oem get-lockstate 
Locked!
fastboot oem get-bootinfo
Unlocked!
```
Then it started. OEM unlock in dev option greyed out.... And not fully unlocked or either locked. Any idea what to do next?
My end goal is to root that device....

Help would be appreciated.

**Comment by plarfman** [comment]
on EMUI 5 or lower, you have to unlock with the code you set to on PotatoNV via fastboot 
fastboot oem unlock (codeyousetto)

**Comment by mashed-potatoes** [comment]
@plarfman test test test

**Comment by AhsanBulbul00** [comment]
Thanks man! Seems to unlock bootloader. But not booting into twrp though...

**Comment by plarfman** [comment]
@AhsanBulbul00 what TWRP are you using? what happens when you try to boot it?

**Comment by AhsanBulbul00** [comment]
Trying to flash twrp, as there isn't prob. other custom recovery for the device. After flashing, when I reboot, takes me straight to normal reboot page.

TWRP official site says to manually go to recovery when `fastboot reboot` ing as, Huawei recovery may auto replace any custom rec.
But not working for me...

**Comment by hleclere** [comment]
I am facing the same issue with Honor 6x unlocked with PotatoNV. The phone is running under EMUI 5.

@AhsanBulbul00 are you saying that using fastboot oem unlock (codeyousetto) did not solve the problem ?

Cheers
