### ISSUE TITLE
will this work for honor 8 lite pra al00x ?

### ISSUE THREAD

**Issue by amrithmmh** [mashed-potatoes/PotatoNV#61]
Hi, 
I am desperate to get the unlock code to root my device. can you add support for hoor 8 lite ra-al00x
HiSilicon Kirin 655
will this tool work?

**Comment by mashed-potatoes** [comment]
@amrithmmh try to read

**Comment by amrithmmh** [comment]
Hi,
I dont want to brick my device. I can see the tool suuports 65X series processor.Thanks for making such an awesome tool!

**Comment by mashed-potatoes** [comment]
@amrithmmh https://github.com/mashed-potatoes/PotatoNV/blob/master/README.md#tested-devices

Huawei P8 Lite (2017) | PRA | Kirin 65x (A)

**Comment by amrithmmh** [comment]
@mashed-potatoes  The device Huawei P8 lite is a different device.
I have Huawei Honor 8 lite - PRA-AL00x
You can add Honor 8 lite - PRA-AL00x to the list of tested devices.
Thanks a lot!

I just tried it anyway and it worked.
For anyone doing this:
read: https://github.com/mashed-potatoes/PotatoNV/wiki/How-to-use-PotatoNV
1. select kirin 65X(A) 
2. enjoy

It works 100% .

**Comment by mashed-potatoes** [comment]
@amrithmmh The brand doesn't matter.
There are no differences (excl. NFC).
