### ISSUE TITLE
Honor 9 STF-L09 not unlock The Bootlader

### ISSUE THREAD

**Issue by RainR56** [mashed-potatoes/PotatoNV#62]
Hi,
i have use PotatoNV to unlock my phone
[stf-l09.log](https://github.com/mashed-potatoes/PotatoNV/files/6411518/stf-l09.log)
, it did not work.
please help me.

**Comment by BudDeuce** [comment]
Are you using fastboot or the test point method?

**Comment by plarfman** [comment]
@RainR56 seems like you are just doing it on locked fastboot, read the instructions and testpoint

**Comment by RainR56** [comment]
@BudDeuce i have use the fastboot method.

**Comment by BudDeuce** [comment]
![](https://4.bp.blogspot.com/-uLex8sDDFu4/XUg08BPxatI/AAAAAAAAYnE/UER7vUIEN0IM7MsvPFXtVVnH39nwnfarQCK4BGAYYCw/s1600/HdAQIlF.jpg)
