### ISSUE TITLE
any success on P20 Pro?

### ISSUE THREAD

**Issue by autoteelar** [mashed-potatoes/PotatoNV#64]
i want to try this but will it work?

**Comment by plarfman** [comment]
@autoteelar Unfortunately, fastboot on Kirin 970/980/710/810 and newer ignores USRKEY & FBLOCK properties in NVME.
So, PotatoNV theoretically can flash the bootloader and update NVME on new SoCs, but this will not affect the bootloader status

in short: no it will not and probably never will be in the near future

**Comment by autoteelar** [comment]
aw that sucks :( i might just cut my losses and sell my P20 pro and find a nice customizable phone

**Comment by plarfman** [comment]
@plarfman not related to PotatoNV tho, so no support for that here

**Comment by EraserCN** [comment]
Kirin 970 not supported yet...
