### ISSUE TITLE
Huawei P9 partition length get error when trying to flash TWRP

### ISSUE THREAD

**Issue by DJGummikuh** [mashed-potatoes/PotatoNV#72]
Hey! I successfully unlocked my phone but now lack the ability to flash twrp because (as far as I understood) my phone is on Android 8 and does not accept the TWRP versions for the P9 (the latest of which was released in 2017. Is there any newer version I can use?

**Comment by DJGummikuh** [comment]
I'm using fastboot flash recovery twrp-3.1.1-0-eva.img (from the twrp download page). Also tried 3.1.0-0 and 3.0.2-0, all with the same response.

I believe the ramdisk stuff came with oreo, but the TWRP versions seem to be too old for that

**Comment by DJGummikuh** [comment]
(to be fair, I'm actually surprised my P9 even got the Android 8 update)

**Comment by BudDeuce** [comment]
Try "fastboot flash recovery_ramdisk twrp-3.1.1-0-eva.img"

**Comment by DJGummikuh** [comment]
I officially like to let you know that I'm an idiot. I always read the ramdisk part as part of the filename, not the command >.<

Thanks for helping me out!

**Comment by BudDeuce** [comment]
No problem.

**Comment by DJGummikuh** [comment]
I need your help once again, I flashed into recovery_ramdisk but when I adb reboot into recovery I get an error mmode "Attention! please update system again! Error! Func NO: 11 (recovery image)
Error NO: 2 (load failed!)
Phone still can boot normally into android but I can't access TWRP like that

**Comment by BudDeuce** [comment]
Which version of TWRP did you flash?

**Comment by DJGummikuh** [comment]
3.1.1.0
this is a bit of a hassle. This guide here says "3.4.0 or later": https://www.getdroidtips.com/root-install-twrp-recovery-huawei-p9/
but the link then points to a download page where I can download 3.1.1.0 as the latest.

**Comment by BudDeuce** [comment]
Try going back 1 version, see what happens.

**Comment by DJGummikuh** [comment]
one version down didnt help, trying the oldest one now (there were 3 files offered)

**Comment by DJGummikuh** [comment]
nope, all 3 offered twrps runninto the same error mode.

**Comment by BudDeuce** [comment]
https://www26.zippyshare.com/v/JI2h29gy/file.html Try the TWRP included in the data folder of this file.

**Comment by DJGummikuh** [comment]
I get a 403 forbidden o.O

**Comment by BudDeuce** [comment]
Weird.

**Comment by DJGummikuh** [comment]
![grafik](https://user-images.githubusercontent.com/5188486/121745211-6a614780-cb04-11eb-8289-f76a5c3f286f.png)

**Comment by BudDeuce** [comment]
https://www26.zippyshare.com/d/JI2h29gy/37226/ROOT_HUAWEI_P9.zip Here is the direct download link.

**Comment by DJGummikuh** [comment]
![grafik](https://user-images.githubusercontent.com/5188486/121745369-81079e80-cb04-11eb-9fef-da796c25e482.png)
Am I stupid or something??

**Comment by BudDeuce** [comment]
No, the TWRP may be EMUI version specific.

**Comment by DJGummikuh** [comment]
flashed the twrp.img from that download file, same result. Func NO:11 Err NO: 2

**Comment by BudDeuce** [comment]
Maybe your EMUI is not compatible with TWRP at the moment.

**Comment by DJGummikuh** [comment]
I mean I want to remove all that and install lineage OS anyways. 
Model: EVA-AL00
Build-Number: EVA-AL00 8.0.0.552(C00)
EMUI-Version: 8.0.0
Android-Version: 8.0.0
Is there a list anywhere that helps me know if TWRP is compatible with that and - if so - which version to get where?

**Comment by BudDeuce** [comment]
https://androidfilehost.com/?fid=1322778262904008816 I finally found a TWRP that is compatible with your EMUI version.

**Comment by BudDeuce** [comment]
https://androidfilehost.com/?fid=1322778262903998750 Sorry, that was for the P9 PLUS, not P9

**Comment by DJGummikuh** [comment]
Where are you from anyways? If we ever cross paths I am SO going to buy you a beer :-D

**Comment by BudDeuce** [comment]
I want to keep my location a secret, but thanks for the complement.

**Comment by DJGummikuh** [comment]
Fair enough

**Comment by DJGummikuh** [comment]
booted into recovery now! you are my hero of the day!

**Comment by DJGummikuh** [comment]
Ok now after flashing lineageOS I entered a boot loop. Have to continue tomorrow
