### ISSUE TITLE
Huawei P8 Lite Alice ALE-L21 2015 rel

### ISSUE THREAD

**Issue by lm212121** [mashed-potatoes/PotatoNV#74]
hello

I have this model, as alice l21 from 2015 hw release. Lot of LOS, twrp or others freedom-oss-like topics on xda regarding p8 lite are about the 2017 rel. I do have the 2015 only.
well, I tried with the potatonv tool to unlock the phone. The operation looks like to success, but unfortunately, even if the screen shows that the bootloader is unlocked.... 

pc ~ # fastboot oem get-lockstate
...
(bootloader) locked
OKAY [  0.001s]
finished. total time: 0.001s
pc ~ # fastboot oem get-bootinfo
...
(bootloader)  unlocked
OKAY [  0.000s]
finished. total time: 0.000s
pc ~ # fastboot flash recovery /tmp/twrp_alice21/recovery.img 
target reported max download size of 471859200 bytes
sending 'recovery' (25152 KB)...
OKAY [  0.627s]
writing 'recovery'...
FAILED (remote: image verification error)
finished. total time: 0.632s

what could I do?

is it possible to communicate with the tool creator Andrey Smirnoff by email, irc or other forum/tchat subject?

I thank you vm

**Comment by BudDeuce** [comment]
Try "recovery_ramdisk" instead of "recovery".

**Comment by lm212121** [comment]
> Try "recovery_ramdisk" instead of "recovery".

fastboot flash recovery_ramdisk /tmp/twrp_alice21/recovery.img 
target reported max download size of 471859200 bytes
sending 'recovery_ramdisk' (25152 KB)...
OKAY [  0.617s]
writing 'recovery_ramdisk'...
FAILED (remote: partition does not exist)
finished. total time: 0.618s

**Comment by BudDeuce** [comment]
Use the bootloader code that PotatoNV gave you and say "fastboot oem unlock bootloadercode"

**Comment by lm212121** [comment]
> Use the bootloader code that PotatoNV gave you and say "fastboot oem unlock bootloadercode"

already tried a dozen of times

**Comment by BudDeuce** [comment]
Did you check the FBLOCK option in PotatoNV?

**Comment by lm212121** [comment]
> Did you check the FBLOCK option in PotatoNV?

yes

**Comment by BudDeuce** [comment]
Which version of PotatoNV did you use?

**Comment by lm212121** [comment]
> Which version of PotatoNV did you use?

2.1.0

**Comment by BudDeuce** [comment]
If you go to the downloads page, there are new versions that contain bug fixes, try those.

**Comment by lm212121** [comment]
> If you go to the downloads page, there are new versions that contain bug fixes, try those.

done today, still same issue : 
 fastboot flash recovery_ramdisk /tmp/twrp_alice21/recovery.img 
target reported max download size of 471859200 bytes
sending 'recovery_ramdisk' (25152 KB)...
OKAY [  0.606s]
writing 'recovery_ramdisk'...
FAILED (remote: partition does not exist)
finished. total time: 0.607s
pc ~ # fastboot flash recovery /tmp/twrp_alice21/recovery.img 
target reported max download size of 471859200 bytes
sending 'recovery' (25152 KB)...
OKAY [  0.594s]
writing 'recovery'...
FAILED (remote: image verification error)
finished. total time: 0.600s
pc ~ # fastboot oem get-bootinfo
...
(bootloader)  unlocked
OKAY [  0.001s]
finished. total time: 0.001s
pc ~ # fastboot oem get-lockstate
...
(bootloader) locked
OKAY [  0.001s]
finished. total time: 0.001s

**Comment by lm212121** [comment]
is there a way to transmit this issue to the potato tool's developper?

**Comment by lm212121** [comment]
.? :-/

**Comment by BudDeuce** [comment]
Yes, there is. @mashed-potatoes

**Comment by lm212121** [comment]
> Yes, there is. @mashed-potatoes

I mean without twitter nor social networks : email for example?
or on a forum?

**Comment by lm212121** [comment]
hey guys, how could I solve the problem of huawei wrongly unlocked through potato?

**Comment by lm212121** [comment]
looks like Im sending  a message in a bottle :
https://forum.xda-developers.com/t/twrp-openkirin-3-1-1-0-all-versions-huawei-p8lite.3583180/post-85398893

**Comment by mashed-potatoes** [comment]
Disable FBLOCK to solve this problem:
```
fastboot oem backdoor set 1
```
Checkbox `Disable FBLOCK` will be disabled for legacy devices in the next release.
