### ISSUE TITLE
[SOLVED] P10 Lite: "The operation has timed out." (logs provided)

### ISSUE THREAD

**Issue by EmanueleCiriachi** [mashed-potatoes/PotatoNV#78]
Connection is achieved as follows:
<img width="182" alt="PotatoNV01" src="https://user-images.githubusercontent.com/7882146/126904374-f69b8c11-3595-4916-90d9-a2429fa64b28.PNG">

Yet this is the result:
<img width="328" alt="PotatoNV02" src="https://user-images.githubusercontent.com/7882146/126904377-e7ee9da4-3980-4e03-899e-862d019d8ada.PNG">

Log is here:
[test.log](https://github.com/mashed-potatoes/PotatoNV/files/6874104/test.log)

What am I doing wrong?

**Comment by mashed-potatoes** [comment]
@EmanueleCiriachi you're using wrong bootloader: https://github.com/mashed-potatoes/PotatoNV#tested-devices.

**Comment by EmanueleCiriachi** [comment]
> @EmanueleCiriachi you're using wrong bootloader: https://github.com/mashed-potatoes/PotatoNV#tested-devices.

I tried all of them, it didn't work...

**Comment by mashed-potatoes** [comment]
@EmanueleCiriachi Ah, I see. You should re-enter vcom mode after each attempt.

**Comment by EmanueleCiriachi** [comment]
It worked! You're a literal savior. I'll go buy you a beer right now!

**Comment by mashed-potatoes** [comment]
ily ❤️
