### ISSUE TITLE
Kickass!

### ISSUE THREAD

**Issue by insaneKane** [mashed-potatoes/PotatoNV#8]
I know thats not what the Issues are ment for but this is an incredible tool.
I tried for quite a long time to unlock my Huawei P Smart and finally this tool is what worked.

So thank you a ton :!

**Comment by ironOmega12** [comment]
Hey man, could you help me use this? I'm bad at programming but I tried to unlock my bootloader for so long..

**Comment by ironOmega12** [comment]
> I know thats not what the Issues are ment for but this is an incredible tool.
> I tried for quite a long time to unlock my Huawei P Smart and finally this tool is what worked.
> 
> So thank you a ton :!

plz

**Comment by mashed-potatoes** [comment]
> I know thats not what the Issues are ment for but this is an incredible tool.
> I tried for quite a long time to unlock my Huawei P Smart and finally this tool is what worked.
> 
> So thank you a ton :!

You're welcome!
If you found this tool helpful and you want to help the community, [consider donating to #niceguys](https://github.com/mashed-potatoes/PotatoNV/issues/10#issuecomment-722551274).

Sincerely,
Andrey
