### ISSUE TITLE
Huawei Y7 prime 2019 orY5p

### ISSUE THREAD

**Issue by mouhsineelachbi** [mashed-potatoes/PotatoNV#92]
Hi
can potatoes NV unlock bootloader in my phones y7 2019 prime and Y5p DRA-LX9 or AMN-LX9 ?

**Comment by mashed-potatoes** [comment]
@mouhsineelachbi no

**Comment by mouhsineelachbi** [comment]
Any idea how can I do It please ?

**Comment by BudDeuce** [comment]
https://hcu-client.com/ is the only one that can unlock your bootloader (reads your bootloader code but you have to manually put it in) source: https://hcu-client.com/supported-models.php

There is one caveat however, it is a paid program.

**Comment by mouhsineelachbi** [comment]
Thank you guys
